stages:
  - build
  - lint
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE: registry.gitlab.com/apprentice.py/class_manager:class_manager_production_image

cache:
  key: ${CI_COMMIT_REF_SLUG}  # Cache per branch
  paths:
    - ${CI_PROJECT_DIR}/classmanager/.venv/


build-production-image:
  image: docker:24.0.6
  services:
    - docker:24.0.6-dind
  stage: build
  before_script:
    - cd classmanager
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY/$CI_PROJECT_PATH
    - docker build -t $IMAGE .
    - docker push $IMAGE
  only:
    changes:
      - classmanager/**/*

lint-code:
  stage: lint
  script:
    - docker pull $IMAGE
    - docker run --name lint_container $IMAGE python -m black . --check
    - docker run --name lint_container $IMAGE python -m isort . --check-only --profile black
  only:
    refs:
      - merge_requests
      - main

security-checks:
  stage: lint
  script:
    - docker pull $IMAGE
    - docker run --name security_container $IMAGE python -m bandit -r .
    - docker run --name security_container $IMAGE python -m safety check
  only:
    refs:
      - merge_requests
      - main

run-tests:
  stage: test
  script:
    - docker pull $IMAGE
    - docker run -d --name test_container -e PORT=8765 -e ENVIRONMENT=dev -e DATABASE_URL=sqlite://sqlite.db -e DATABASE_TEST_URL=sqlite://sqlite_test.db $IMAGE
    - docker exec test_container python -m pytest --junitxml=report.xml --cov=./ --cov-report=xml tests/**/*
  only:
    refs:
      - merge_requests
      - main